In [119]:
from numpy import *

# define the number of movies in our 'database'
num_movies = 9

# define the number of users in our 'database'

num_users = 5

# randomly initialize some movie ratings 
# a 10 X 5 matrix

ratings = random.randint(11, size = (num_movies, num_users))

did_rate = (ratings != 0) * 1

# Let's make some ratings. A 10 X 1 column vector to store all the ratings I make

ratings.shape

(9, 5)

In [120]:
new_movie_ratings = random.randint(1, size = (1, num_users))
new_movie_ratings

array([[0, 0, 0, 0, 0]])

In [121]:
ratings = append(new_movie_ratings, ratings, axis = 0)
did_rate = append(((new_movie_ratings != 0) * 1), did_rate, axis = 0)
ratings

array([[ 0,  0,  0,  0,  0],
       [ 2,  3,  2,  1, 10],
       [ 5,  3,  7,  0,  0],
       [ 9,  3,  1, 10,  1],
       [ 9,  2,  9, 10,  5],
       [ 9,  3,  3,  0,  4],
       [ 6,  1,  4,  6,  6],
       [ 3,  5,  4,  4,  7],
       [ 1,  5,  9,  1,  8],
       [ 2, 10,  8,  8,  6]])

In [122]:
did_rate

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [123]:
num_movies = ratings.shape[0]

my_ratings = zeros((num_movies, 1))



# I rate 3 movies

my_ratings[1] = 8
my_ratings[4] = 7
my_ratings[7] = 3

In [124]:
my_ratings

array([[ 0.],
       [ 8.],
       [ 0.],
       [ 0.],
       [ 7.],
       [ 0.],
       [ 0.],
       [ 3.],
       [ 0.],
       [ 0.]])

In [125]:
# Update ratings and did_rate
# Update ratings and did_rate

ratings = append(my_ratings, ratings, axis = 1)
did_rate = append(((my_ratings != 0) * 1), did_rate, axis = 1)

In [126]:
ratings.shape

(10, 6)

In [127]:
# a function that normalizes a dataset

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean


In [128]:
# Normalize ratings
ratings, ratings_mean = normalize_ratings(ratings, did_rate)

/home/ubuntu/python-projects/env-2/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/ubuntu/python-projects/env-2/lib/python3.5/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [129]:
ratings

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 3.66666667, -2.33333333, -1.33333333, -2.33333333, -3.33333333,
         5.66666667],
       [ 0.        ,  0.        , -2.        ,  2.        ,  0.        ,
         0.        ],
       [ 0.        ,  4.2       , -1.8       , -3.8       ,  5.2       ,
        -3.8       ],
       [ 0.        ,  2.        , -5.        ,  2.        ,  3.        ,
        -2.        ],
       [ 0.        ,  4.25      , -1.75      , -1.75      ,  0.        ,
        -0.75      ],
       [ 0.        ,  1.4       , -3.6       , -0.6       ,  1.4       ,
         1.4       ],
       [-1.33333333, -1.33333333,  0.66666667, -0.33333333, -0.33333333,
         2.66666667],
       [ 0.        , -3.8       ,  0.2       ,  4.2       , -3.8       ,
         3.2       ],
       [ 0.        , -4.8       ,  3.2       ,  1.2       ,  1.2       ,
        -0.8       ]])

In [148]:
ratings_mean[0] = 0
ratings_mean

array([[ 0.        ],
       [ 4.33333333],
       [ 5.        ],
       [ 4.8       ],
       [ 7.        ],
       [ 4.75      ],
       [ 4.6       ],
       [ 4.33333333],
       [ 4.8       ],
       [ 6.8       ]])

In [131]:
# Update some key variables now

num_users = ratings.shape[1]
num_features = 3

In [132]:
# Initialize Parameters theta (user_prefs), X (movie_features)

movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

In [133]:
movie_features

array([[-0.8513355 ,  0.14300732, -0.99740413],
       [ 1.70404305,  0.72484476, -0.39452052],
       [-0.33085261, -1.48620845, -0.15567242],
       [-0.83138771,  1.81056635, -1.90218716],
       [-0.8017672 , -1.8490249 , -0.11820789],
       [-2.02711448,  1.53089275, -1.84184965],
       [-0.15898463, -1.34413325,  1.70756455],
       [ 0.73039197, -0.36461704,  0.17153173],
       [-1.94134601, -0.66961412, -0.57772974],
       [ 2.00847948, -0.65803738, -0.16730528]])

In [134]:
user_prefs

array([[-1.09595491, -0.50415222,  0.96141491],
       [ 0.72117662, -3.08826755,  0.91952496],
       [-1.50326083,  0.57275938, -0.12230561],
       [-0.44163551, -1.68556791, -0.58758646],
       [ 0.26088895, -0.97421592,  1.3611566 ],
       [ 0.5262364 , -0.15325263,  0.27479996]])

In [135]:
initial_X_and_theta

array([-0.8513355 ,  1.70404305, -0.33085261, -0.83138771, -0.8017672 ,
       -2.02711448, -0.15898463,  0.73039197, -1.94134601,  2.00847948,
        0.14300732,  0.72484476, -1.48620845,  1.81056635, -1.8490249 ,
        1.53089275, -1.34413325, -0.36461704, -0.66961412, -0.65803738,
       -0.99740413, -0.39452052, -0.15567242, -1.90218716, -0.11820789,
       -1.84184965,  1.70756455,  0.17153173, -0.57772974, -0.16730528,
       -1.09595491,  0.72117662, -1.50326083, -0.44163551,  0.26088895,
        0.5262364 , -0.50415222, -3.08826755,  0.57275938, -1.68556791,
       -0.97421592, -0.15325263,  0.96141491,  0.91952496, -0.12230561,
       -0.58758646,  1.3611566 ,  0.27479996])

In [136]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
	# Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
	# --------------------------------------------------------------------------------------------------------------
	# Get the first 30 (10 * 3) rows in the 48 X 1 column vector
	first_30 = X_and_theta[:num_movies * num_features]
	# Reshape this column vector into a 10 X 3 matrix
	X = first_30.reshape((num_features, num_movies)).transpose()
	# Get the rest of the 18 the numbers, after the first 30
	last_18 = X_and_theta[num_movies * num_features:]
	# Reshape this column vector into a 6 X 3 matrix
	theta = last_18.reshape(num_features, num_users ).transpose()
	return X, theta

In [137]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply by did_rate because we only want to consider observations for which a rating was given
	difference = X.dot( theta.T ) * did_rate - ratings
	X_grad = difference.dot( theta ) + reg_param * X
	theta_grad = difference.T.dot( X ) + reg_param * theta
	
	# wrap the gradients back into a column vector 
	return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [138]:
reg_param = 30
gradient = calculate_gradient(initial_X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param)
gradient.shape

(48,)

In [139]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	# we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
	cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
	# '**' means an element-wise power
	regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
	return cost + regularization

In [140]:

cost = calculate_cost(initial_X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param)

In [141]:
cost

1403.0735084349253

In [142]:
# import these for advanced optimizations (like gradient descent)

from scipy import optimize

In [143]:
# regularization paramater

reg_param = 30

# perform gradient descent, find the minimum cost (sum of squared errors) and optimal values of X (movie_features) and Theta (user_prefs)

minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, 								args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), 								maxiter=100, disp=True, full_output=True ) 

cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]


# unroll once again

movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

Optimization terminated successfully.
         Current function value: 174.508333
         Iterations: 12
         Function evaluations: 24
         Gradient evaluations: 24


In [154]:
movie_features

array([[  1.87538127e-08,  -3.15026506e-09,   2.19715145e-08],
       [ -3.34416535e-07,  -3.70530536e-07,   1.54242372e-07],
       [  1.74992599e-08,   4.38311610e-08,  -1.25972114e-09],
       [  3.88642679e-08,  -6.45794377e-08,   2.47421833e-08],
       [  6.75343006e-08,   4.88397972e-08,  -8.19143269e-09],
       [ -1.61189731e-07,  -1.06427809e-07,   1.10173652e-07],
       [ -6.44767848e-08,  -1.85301383e-07,   8.25579333e-08],
       [  2.39243320e-08,  -1.30265598e-07,   8.70723170e-08],
       [  4.84044081e-08,   5.12927308e-08,   1.21274125e-08],
       [  2.59895292e-07,   1.82079535e-07,  -1.38676869e-07]])

In [155]:
user_prefs

array([[ -2.28888608e-07,  -1.10080155e-07,  -3.07789877e-08],
       [ -2.83182737e-08,  -1.90855571e-07,   1.95560635e-08],
       [  1.11309413e-07,   2.92331688e-07,  -2.32789617e-07],
       [ -5.00807636e-08,   1.44175866e-07,  -4.71833550e-08],
       [  1.22126746e-07,   2.07134014e-07,   3.36914623e-08],
       [  6.94056839e-08,  -3.10906860e-07,   2.41193287e-07]])

In [156]:
# Make some predictions (movie recommendations). Dot product
all_predictions = movie_features.dot( user_prefs.T )
all_predictions

array([[ -4.62201339e-15,   4.99846370e-16,  -3.94818688e-15,
         -2.43008722e-15,   2.37806753e-15,   7.58044202e-15],
       [  1.12584770e-13,   8.32042897e-14,  -1.81447548e-13,
         -4.39513982e-14,  -1.12394029e-13,   1.29192302e-13],
       [ -8.79154930e-15,  -8.88560530e-15,   1.50543196e-14,
          5.50245719e-15,   1.11736101e-14,  -1.27166968e-14],
       [ -2.54821305e-15,   1.17086362e-14,  -2.03123806e-14,
         -1.24245678e-14,  -7.79663119e-15,   2.87432398e-14],
       [ -2.05820005e-14,  -1.13939944e-14,   2.37015042e-14,
          4.04585002e-15,   1.80881463e-14,  -1.24730822e-14],
       [  4.52190494e-14,   2.70315181e-14,  -7.47014375e-14,
         -1.24701793e-14,  -3.80184852e-14,   4.84747975e-14],
       [  3.26149569e-14,   3.88061807e-14,  -8.05649688e-14,
         -2.73823011e-14,  -4.34750616e-14,   7.30488350e-14],
       [  6.18365237e-15,   2.58872111e-14,  -5.56872901e-14,
         -2.40876683e-14,  -2.11270416e-14,   6.31622109e-14],


In [167]:
predictions_for_me = all_predictions[:, 0:1] + ratings_mean
predictions_for_me

array([[ -4.62201339e-15],
       [  8.66666667e+00],
       [  1.00000000e+01],
       [  9.60000000e+00],
       [  1.40000000e+01],
       [  9.50000000e+00],
       [  9.20000000e+00],
       [  8.66666667e+00],
       [  9.60000000e+00],
       [  1.36000000e+01]])

In [152]:
my_ratings

array([[ 0.],
       [ 8.],
       [ 0.],
       [ 0.],
       [ 7.],
       [ 0.],
       [ 0.],
       [ 3.],
       [ 0.],
       [ 0.]])

In [164]:
predictions_for_me2 = all_predictions[:, 1:2] + ratings_mean

In [166]:
predictions_for_me2

array([[  4.99846370e-16],
       [  8.66666667e+00],
       [  1.00000000e+01],
       [  9.60000000e+00],
       [  1.40000000e+01],
       [  9.50000000e+00],
       [  9.20000000e+00],
       [  8.66666667e+00],
       [  9.60000000e+00],
       [  1.36000000e+01]])